#!/usr/bin/env bash
# scaffold_lib.sh: Generation functions for scaffold-ci.
# Sourced by scripts/scaffold-ci. Not executed directly.

# Sourced global vars expected: REL_CI, _pf_project, _pf_tier,
# _pf_languages, _pf_override_ids, _pf_override_fields,
# _pf_override_values, _reg_*, _PARSER, _QE_TEMPLATE, _CONFIG_DIR.

# ── Render a hook's entry string ───────────────────────────────────────────
_scl_render_entry() {
    local _hid="$1"
    local _kind="${_reg_kind[$_hid]}"
    local _entry="${_reg_entry[$_hid]}"
    local _i
    for _i in "${!_pf_override_ids[@]}"; do
        if [[ "${_pf_override_ids[$_i]}" == "$_hid" && "${_pf_override_fields[$_i]}" == "entry" ]]; then
            printf '%s' "${_pf_override_values[$_i]}"
            return
        fi
    done
    case "$_kind" in
        shell)
            printf "bash -c 'source %s/lib/checks.sh && %s'" "$REL_CI" "$_entry" ;;
        shell_inline)
            printf '%s' "$_entry" ;;
        shell_with_arg)
            printf "bash -c 'source %s/lib/checks.sh && %s \"\$1\"' --" "$REL_CI" "$_entry" ;;
        python_module)
            printf "%s/.venv/bin/python -m %s" "$REL_CI" "$_entry" ;;
        python_module_files)
            printf "%s/.venv/bin/python -m %s \"\$@\"" "$REL_CI" "$_entry" ;;
        makefile_target)
            printf "make %s" "$_entry" ;;
        *)
            ci_fail "Unknown hook kind '$_kind' for hook '$_hid'"
            exit 1 ;;
    esac
}

# ── Get a hook field with override support ─────────────────────────────────
_scl_get_field() {
    local _hid="$1" _field="$2" _default="$3"
    local _i
    for _i in "${!_pf_override_ids[@]}"; do
        if [[ "${_pf_override_ids[$_i]}" == "$_hid" && "${_pf_override_fields[$_i]}" == "$_field" ]]; then
            printf '%s' "${_pf_override_values[$_i]}"
            return
        fi
    done
    case "$_field" in
        pass_filenames) printf '%s' "${_reg_pass_fn[$_hid]:-$_default}" ;;
        always_run)     printf '%s' "${_reg_always[$_hid]:-$_default}" ;;
        files)          printf '%s' "${_reg_files[$_hid]:-}" ;;
        *)              printf '%s' "$_default" ;;
    esac
}

# ── Generate .pre-commit-config.yaml content ───────────────────────────────
_scl_gen_precommit() {
    local _ts; _ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '# AUTO-GENERATED by %s/scripts/scaffold-ci [%s]\n' "$REL_CI" "$_ts"
    printf '# Source: ci-profile.yaml | tier=%s | languages=%s\n' "$_pf_tier" "${_pf_languages[*]}"
    printf '# Re-generate: make -C %s scaffold-ci CONSUMER=. --force\n' "$REL_CI"
    printf 'repos:\n  - repo: local\n    hooks:\n'
    local _stage _sname _vname _hid
    for _stage in "pre-commit:pre_commit" "commit-msg:commit_msg" "pre-push:pre_push"; do
        _sname="${_stage%%:*}"
        _vname="${_stage#*:}"
        local -n _sarr="_pf_hooks_$_vname"
        for _hid in "${_sarr[@]:-}"; do
            if [[ -z "$_hid" ]]; then continue; fi
            local _name="${_hid//-/ }"
            _name="$(echo "$_name" | awk '{for(i=1;i<=NF;i++)$i=toupper(substr($i,1,1))substr($i,2)}1')"
            local _entry; _entry="$(_scl_render_entry "$_hid")"
            local _pf; _pf="$(_scl_get_field "$_hid" pass_filenames "true")"
            local _ar; _ar="$(_scl_get_field "$_hid" always_run "false")"
            local _files; _files="$(_scl_get_field "$_hid" files "")"
            printf '      - id: %s\n' "$_hid"
            printf '        name: %s\n' "\"$_name\""
            printf '        entry: %s\n' "\"$_entry\""
            printf '        language: system\n'
            printf '        pass_filenames: %s\n' "$_pf"
            printf '        always_run: %s\n' "$_ar"
            if [[ "$_sname" != "pre-commit" ]]; then
                printf '        stages: [%s]\n' "$_sname"
            fi
            if [[ -n "$_files" ]]; then
                printf '        files: %s\n' "\"$_files\""
            fi
        done
    done
}

# ── Generate Makefile content from template ────────────────────────────────
_scl_gen_makefile() {
    local _ts; _ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    local _tpl="$_CI_ROOT/templates/Makefile.consumer"
    [[ -f "$_tpl" ]] || { ci_fail "Makefile template not found: $_tpl"; exit 1; }
    sed \
        -e "s|__REL_CI__|$REL_CI|g" \
        -e "s|__PROJECT__|$_pf_project|g" \
        -e "s|__LANGUAGES__|${_pf_languages[*]}|g" \
        -e "s|__TIER__|$_pf_tier|g" \
        -e "s|__TIMESTAMP__|$_ts|g" \
        -e "s|__CONSUMER__|$_consumer|g" \
        "$_tpl"
}

# ── Copy a config file with optional post-processing ───────────────────────
_scl_copy_config() {
    local _src="$1" _dst="$2" _pp="$3"
    if [[ -f "$_dst" && $_force -eq 0 ]]; then
        if ! diff -q "$_src" "$_dst" > /dev/null 2>&1; then
            _skipped+=("$_dst (customized, use --force)")
            return
        fi
    fi
    local _content
    if [[ "$_pp" == "coverage" ]]; then
        _content="$(sed "s/source_path: ci/source_path: $_pf_project/g" "$_src")"
    elif [[ "$_pp" == "dead_code" ]]; then
        local _scan_val="[]"
        for _lang in "${_pf_languages[@]}"; do
            case "$_lang" in rust) _scan_val="[src]" ;; esac
        done
        _content="$(sed "s/scan_paths:/scan_paths:/" "$_src" | awk -v val="$_scan_val" '
            /^scan_paths:/ { print "scan_paths: " val; next }
            /^  - ci$/ { next }
            { print }
        ')"
    else
        _content="$(cat "$_src")"
    fi
    if [[ $_dry_run -eq 1 ]]; then
        echo "================================================================================"
        echo "Would write: $_dst"
        echo "================================================================================"
        printf '%s\n' "$_content"
    else
        mkdir -p "$(dirname "$_dst")"
        printf '%s\n' "$_content" > "$_dst"
        _generated+=("$_dst")
    fi
}

# ── Generate quality_exceptions.yaml ───────────────────────────────────────
_scl_gen_qe() {
    local _dst="$_consumer/quality_exceptions.yaml"
    if [[ -f "$_dst" ]]; then
        _skipped+=("$_dst (exists, never overwritten)")
        return
    fi
    local _content; _content="$(sed "s/__PROJECT_NAME__/$_pf_project/g" "$_QE_TEMPLATE")"
    if [[ $_dry_run -eq 1 ]]; then
        echo "================================================================================"
        echo "Would write: $_dst"
        echo "================================================================================"
        printf '%s\n' "$_content"
    else
        printf '%s\n' "$_content" > "$_dst"
        _generated+=("$_dst")
    fi
}

# ── Build template stage arrays from registry ─────────────────────────────
_scl_build_tpl_stages() {
    local _rid
    for _rid in "${!_reg_id[@]}"; do
        local _stage="${_reg_stage[$_rid]}"
        local _safety="${_reg_safety[$_rid]}"
        local _mandatory="${_reg_mandatory[$_rid]}"
        local _sk="1"
        if [[ "$_safety" == "true" ]]; then _sk="0"; fi
        local _mk="1"
        if [[ "$_mandatory" == "true" ]]; then _mk="0"; fi
        local _key="${_sk}${_mk}_${_rid}"
        case "$_stage" in
            pre-commit)  _tpl_pc+=("$_key:$_rid") ;;
            commit-msg)  _tpl_cm+=("$_key:$_rid") ;;
            pre-push)    _tpl_pp+=("$_key:$_rid") ;;
        esac
    done
    return 0
}

# ── Generate ci-profile.template.yaml content ─────────────────────────────
_scl_gen_template() {
    local _ts; _ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '# ci-profile.template.yaml: reference profile generated from\n'
    printf '# config/required_hooks.yaml by scripts/scaffold-ci --emit-template.\n'
    printf '# Copy this to <consumer>/ci-profile.yaml and trim per-project.\n'
    printf '# DO NOT edit this template by hand; regenerate it via\n'
    printf '# make scaffold-ci ARGS=--emit-template.\n'
    local _total=0 _stage_counts=""
    local _sname _entry
    for _sname in "pre-commit:_tpl_pc_sorted" "commit-msg:_tpl_cm_sorted" "pre-push:_tpl_pp_sorted"; do
        local _name="${_sname%%:*}"
        local _var="${_sname#*:}"
        local -n _arr="$_var"
        local _count=0
        printf '\n%s:\n' "$_name"
        for _entry in "${_arr[@]:-}"; do
            if [[ -z "$_entry" ]]; then continue; fi
            printf '  - %s\n' "${_entry##*:}"
            _count=$((_count + 1))
        done
        _total=$((_total + _count))
        _stage_counts="$_stage_counts $_name=$_count"
    done
    printf '\n# Total hooks: %d (%s)\n' "$_total" "${_stage_counts# }"
    printf '# Generated: %s\n' "$_ts"
    printf '# Source: config/required_hooks.yaml\n'
}
