#!/usr/bin/env bash
# scaffold_lib.sh: Generation functions for scaffold-ci.
# Sourced by scripts/scaffold-ci. Not executed directly.

# Sourced global vars expected: REL_CI, _pf_project, _pf_tier,
# _pf_languages, _pf_override_ids, _pf_override_fields,
# _pf_override_values, _reg_*, _PARSER, _QE_TEMPLATE, _CONFIG_DIR.

# ── Backup a file before overwrite ─────────────────────────────────────────
# _scl_backup <path> <make_backup_flag> <nameref_array>
# Copies <path> to <path>.scaffold-bak.<epoch> if make_backup_flag is 1 and the
# file exists, then appends the backup path to the nameref'd array so the caller
# can report it in the summary. No-op when the file is absent or flag is 0.
_scl_backup() {
    local _path="$1" _flag="$2"
    local -n _arr="$3"
    [[ $_flag -eq 1 && -f "$_path" ]] || return 0
    local _bak="${_path}.scaffold-bak.$(date +%s)"
    cp -p "$_path" "$_bak"
    _arr+=("$_bak")
}

# ── Render a hook's entry string ───────────────────────────────────────────
_scl_render_entry() {
    local _hid="$1"
    local _kind="${_reg_kind[$_hid]}"
    local _entry="${_reg_entry[$_hid]}"
    local _i
    for _i in "${!_pf_override_ids[@]}"; do
        if [[ "${_pf_override_ids[$_i]}" == "$_hid" && "${_pf_override_fields[$_i]}" == "entry" ]]; then
            printf '%s' "${_pf_override_values[$_i]}"
            return
        fi
    done
    case "$_kind" in
        shell)
            printf "bash -c 'source %s/lib/checks.sh && %s'" "$REL_CI" "$_entry" ;;
        shell_inline)
            printf '%s' "$_entry" ;;
        shell_with_arg)
            printf "bash -c 'source %s/lib/checks.sh && %s \"\$1\"' --" "$REL_CI" "$_entry" ;;
        python_module)
            printf "%s/.venv/bin/python -m %s" "$REL_CI" "$_entry" ;;
        python_module_files)
            printf "%s/.venv/bin/python -m %s \"\$@\"" "$REL_CI" "$_entry" ;;
        makefile_target)
            printf "make %s" "$_entry" ;;
        *)
            ci_fail "Unknown hook kind '$_kind' for hook '$_hid'"
            exit 1 ;;
    esac
}

# ── Get a hook field with override support ─────────────────────────────────
_scl_get_field() {
    local _hid="$1" _field="$2" _default="$3"
    local _i
    for _i in "${!_pf_override_ids[@]}"; do
        if [[ "${_pf_override_ids[$_i]}" == "$_hid" && "${_pf_override_fields[$_i]}" == "$_field" ]]; then
            printf '%s' "${_pf_override_values[$_i]}"
            return
        fi
    done
    case "$_field" in
        pass_filenames) printf '%s' "${_reg_pass_fn[$_hid]:-$_default}" ;;
        always_run)     printf '%s' "${_reg_always[$_hid]:-$_default}" ;;
        files)          printf '%s' "${_reg_files[$_hid]:-}" ;;
        *)              printf '%s' "$_default" ;;
    esac
}

# ── Generate .pre-commit-config.yaml content ───────────────────────────────
_scl_gen_precommit() {
    local _ts; _ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '# AUTO-GENERATED by %s/scripts/scaffold-ci [%s]\n' "$REL_CI" "$_ts"
    printf '# Source: ci-profile.yaml | tier=%s | languages=%s\n' "$_pf_tier" "${_pf_languages[*]}"
    printf '# Re-generate (safe, pre-commit only): make -C %s scaffold-ci CONSUMER=. --force-precommit --yes\n' "$REL_CI"
    printf '# WARNING: --force-all overwrites Makefile + config/*.\n' "$REL_CI"
    printf '#          --force is removed; use --force-precommit | --force-makefile | --force-configs | --force-all.\n'
    printf 'repos:\n  - repo: local\n    hooks:\n'
    local _stage _sname _vname _hid
    for _stage in "pre-commit:pre_commit" "commit-msg:commit_msg" "pre-push:pre_push"; do
        _sname="${_stage%%:*}"
        _vname="${_stage#*:}"
        local -n _sarr="_pf_hooks_$_vname"
        for _hid in "${_sarr[@]:-}"; do
            if [[ -z "$_hid" ]]; then continue; fi
            local _name="${_hid//-/ }"
            _name="$(echo "$_name" | awk '{for(i=1;i<=NF;i++)$i=toupper(substr($i,1,1))substr($i,2)}1')"
            local _entry; _entry="$(_scl_render_entry "$_hid")"
            local _pf; _pf="$(_scl_get_field "$_hid" pass_filenames "true")"
            local _ar; _ar="$(_scl_get_field "$_hid" always_run "false")"
            local _files; _files="$(_scl_get_field "$_hid" files "")"
            printf '      - id: %s\n' "$_hid"
            printf '        name: %s\n' "\"$_name\""
            printf '        entry: %s\n' "\"$_entry\""
            printf '        language: system\n'
            printf '        pass_filenames: %s\n' "$_pf"
            printf '        always_run: %s\n' "$_ar"
            if [[ "$_sname" != "pre-commit" ]]; then
                printf '        stages: [%s]\n' "$_sname"
            fi
            if [[ -n "$_files" ]]; then
                printf '        files: %s\n' "\"$_files\""
            fi
        done
    done
}

# ── Generate Makefile content from template ────────────────────────────────
_scl_gen_makefile() {
    local _ts; _ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    local _tpl="$_CI_ROOT/templates/Makefile.consumer"
    [[ -f "$_tpl" ]] || { ci_fail "Makefile template not found: $_tpl"; exit 1; }
    sed \
        -e "s|__REL_CI__|$REL_CI|g" \
        -e "s|__PROJECT__|$_pf_project|g" \
        -e "s|__LANGUAGES__|${_pf_languages[*]}|g" \
        -e "s|__TIER__|$_pf_tier|g" \
        -e "s|__TIMESTAMP__|$_ts|g" \
        -e "s|__CONSUMER__|$_consumer|g" \
        "$_tpl"
}

# ── Render a config file's content (no disk I/O) ─────────────────────────
# _scl_render_config <src> <postproc> <consumer_dir>
# Returns the post-processed config content as stdout. For the "dead_code"
# postproc, prefers the existing on-disk scan_paths over the language-based
# guess so a hand-edited src/ entry is preserved (the previous logic reset
# scan_paths to [] for any non-rust language, quietly disabling the scan).
# For "coverage", preserves any existing unit.* fields instead of letting the
# sed source_path substitution clobber per-stack test runner config.
_scl_render_config() {
    local _src="$1" _pp="$2" _consumer_dir="${3:-}"
    local _content
    if [[ "$_pp" == "coverage" ]]; then
        _content="$(sed "s/source_path: ci/source_path: $_pf_project/g" "$_src")"
        # Preserve existing unit.* fields from any on-disk copy.
        if [[ -n "$_consumer_dir" && -f "$_consumer_dir/config/coverage_thresholds.yaml" ]]; then
            local _existing _preserved
            _existing="$(cat "$_consumer_dir/config/coverage_thresholds.yaml")"
            _preserved="$(printf '%s\n' "$_existing" | awk '
                /^unit\.path:/      { upath=$0 }
                /^unit\.runner:/    { urunner=$0 }
                /^unit\.coverage:/  { ucov=$0 }
                END {
                    if (upath   != "") print upath
                    if (urunner != "") print urunner
                    if (ucov    != "") print ucov
                }
            ')"
            if [[ -n "$_preserved" ]]; then
                local _filtered
                _filtered="$(printf '%s\n' "$_content" | grep -vE '^unit\.(path|runner|coverage):')"
                _content="$_filtered
$_preserved"
            fi
        fi
    elif [[ "$_pp" == "dead_code" ]]; then
        local _scan_val="[]"
        for _lang in "${_pf_languages[@]}"; do
            case "$_lang" in rust) _scan_val="[src]" ;; esac
        done
        # Prefer existing on-disk scan_paths if the value is non-empty.
        if [[ -n "$_consumer_dir" && -f "$_consumer_dir/config/dead_code.yaml" ]]; then
            local _existing_scan
            _existing_scan="$(awk -F': ' '/^scan_paths:/ { print $2 }' "$_consumer_dir/config/dead_code.yaml")"
            if [[ -n "$_existing_scan" && "$_existing_scan" != "[]" ]]; then
                _scan_val="$_existing_scan"
            fi
        fi
        _content="$(sed "s/scan_paths:/scan_paths:/" "$_src" | awk -v val="$_scan_val" '
            /^scan_paths:/ { print "scan_paths: " val; next }
            /^  - ci$/ { next }
            { print }
        ')"
    else
        _content="$(cat "$_src")"
    fi
    printf '%s' "$_content"
}

# ── Strip the volatile AUTO-GENERATED timestamp line ───────────────────────
# Reads stdin, writes stdout with lines matching the embedded-timestamp
# generator header removed. Lets refresh-vs-customized comparison ignore
# the always-changing timestamp in .pre-commit-config.yaml and Makefile.
_scl_strip_ts() {
    awk '!/^# AUTO-GENERATED by .* \[/'
}

# ── Determine on-disk state for a generated file ──────────────────────────
# _scl_state <rendered_content> <path>
# Echoes one of: MISSING | IN_SYNC | CUSTOMIZED
_scl_state() {
    local _rendered="$1" _path="$2"
    if [[ ! -f "$_path" ]]; then
        printf 'MISSING'
        return
    fi
    local _r _e
    _r="$(printf '%s\n' "$_rendered" | _scl_strip_ts)"
    _e="$(cat "$_path" | _scl_strip_ts)"
    if [[ "$_r" == "$_e" ]]; then
        printf 'IN_SYNC'
    else
        printf 'CUSTOMIZED'
    fi
}

# ── Copy a config file with optional post-processing ───────────────────────
# _scl_copy_config <src> <dst> <postproc> <force_flag> <make_backup_flag>
# <force_flag> is 1 only when --force-configs or --force-all is set.
# A customised dst (differs from rendered content modulo the timestamp header)
# is skipped unless force_flag. When force_flag overwrites a customised file,
# a backup is written first.
_scl_copy_config() {
    local _src="$1" _dst="$2" _pp="$3" _force_this="$4" _make_backup="$5"
    local _content
    _content="$(_scl_render_config "$_src" "$_pp" "$_consumer")"
    if [[ -f "$_dst" ]]; then
        if [[ "$(_scl_state "$_content" "$_dst")" == "IN_SYNC" ]]; then
            _skipped+=("$_dst (in sync)")
            return
        elif [[ $_force_this -eq 0 ]]; then
            _skipped+=("$_dst (customized; refresh with --force-configs, diff with --diff)")
            return
        fi
    fi
    if [[ $_dry_run -eq 1 ]]; then
        echo "================================================================================"
        echo "Would write: $_dst"
        echo "================================================================================"
        printf '%s\n' "$_content"
    else
        mkdir -p "$(dirname "$_dst")"
        _scl_backup "$_dst" "$_make_backup" _backups_written
        printf '%s\n' "$_content" > "$_dst"
        _generated+=("$_dst")
    fi
}

# ── Generate quality_exceptions.yaml ───────────────────────────────────────
_scl_gen_qe() {
    local _dst="$_consumer/quality_exceptions.yaml"
    if [[ -f "$_dst" ]]; then
        _skipped+=("$_dst (exists, never overwritten)")
        return
    fi
    local _content; _content="$(sed "s/__PROJECT_NAME__/$_pf_project/g" "$_QE_TEMPLATE")"
    if [[ $_dry_run -eq 1 ]]; then
        echo "================================================================================"
        echo "Would write: $_dst"
        echo "================================================================================"
        printf '%s\n' "$_content"
    else
        printf '%s\n' "$_content" > "$_dst"
        _generated+=("$_dst")
    fi
}

# ── Build template stage arrays from registry ─────────────────────────────
_scl_build_tpl_stages() {
    local _rid
    for _rid in "${!_reg_id[@]}"; do
        local _stage="${_reg_stage[$_rid]}"
        local _safety="${_reg_safety[$_rid]}"
        local _mandatory="${_reg_mandatory[$_rid]}"
        local _sk="1"
        if [[ "$_safety" == "true" ]]; then _sk="0"; fi
        local _mk="1"
        if [[ "$_mandatory" == "true" ]]; then _mk="0"; fi
        local _key="${_sk}${_mk}_${_rid}"
        case "$_stage" in
            pre-commit)  _tpl_pc+=("$_key:$_rid") ;;
            commit-msg)  _tpl_cm+=("$_key:$_rid") ;;
            pre-push)    _tpl_pp+=("$_key:$_rid") ;;
        esac
    done
    return 0
}

# ── Generate ci-profile.template.yaml content ─────────────────────────────
_scl_gen_template() {
    local _ts; _ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '# ci-profile.template.yaml: reference profile generated from\n'
    printf '# config/required_hooks.yaml by scripts/scaffold-ci --emit-template.\n'
    printf '# Copy this to <consumer>/ci-profile.yaml and trim per-project.\n'
    printf '# DO NOT edit this template by hand; regenerate it via\n'
    printf '# make scaffold-ci ARGS=--emit-template.\n'
    local _total=0 _stage_counts=""
    local _sname _entry
    for _sname in "pre-commit:_tpl_pc_sorted" "commit-msg:_tpl_cm_sorted" "pre-push:_tpl_pp_sorted"; do
        local _name="${_sname%%:*}"
        local _var="${_sname#*:}"
        local -n _arr="$_var"
        local _count=0
        printf '\n%s:\n' "$_name"
        for _entry in "${_arr[@]:-}"; do
            if [[ -z "$_entry" ]]; then continue; fi
            printf '  - %s\n' "${_entry##*:}"
            _count=$((_count + 1))
        done
        _total=$((_total + _count))
        _stage_counts="$_stage_counts $_name=$_count"
    done
    printf '\n# Total hooks: %d (%s)\n' "$_total" "${_stage_counts# }"
    printf '# Generated: %s\n' "$_ts"
    printf '# Source: config/required_hooks.yaml\n'
}

# ── Extract Makefile target names from a file ────────────────────────────
# _scl_extract_targets <path>
# Prints one target name per line (lines matching ^name: where name starts
# with a letter and contains [A-Za-z0-9_.-]). Comments and indented recipe
# lines are excluded.
_scl_extract_targets() {
    awk '/^[A-Za-z][A-Za-z0-9_.-]*:/ {
        name = $0
        sub(/:.*/, "", name)
        print name
    }' "$1"
}

# ── Extract Makefile target names from stdin ──────────────────────────────
# Same as _scl_extract_targets but reads from stdin (for rendered strings).
_scl_extract_targets_stdin() {
    awk '/^[A-Za-z][A-Za-z0-9_.-]*:/ {
        name = $0
        sub(/:.*/, "", name)
        print name
    }'
}

# ── Inspection-mode functions live in scaffold_analyze.sh ──────────────────
# (analyze, diff, json, append-makefile, hook-drift, override checks).
# Sourced here so callers only need to source scaffold_lib.sh.
if ! source "$_CI_ROOT/lib/scaffold_analyze.sh"; then
    echo "ERROR: failed to source $_CI_ROOT/lib/scaffold_analyze.sh" >&2
    exit 2
fi


