# scaffold-ci custom-hook lift and merge tests.
# Sourced by run_tests_unit.sh, requires test_helpers.sh loaded first.

echo ""
echo "=== scaffold-ci custom-hook lift tests ==="

_SCI_SCRIPT="$PROJECT_DIR/scripts/scaffold-ci"

_mk_custom_consumer() {
    local _dir="$1"
    mkdir -p "$_dir"
    cat > "$_dir/ci-profile.yaml" <<'EOF'
version: 1
project: custom-test
tier: strict
languages: [any]
hooks:
  pre-commit: [check-unstaged, my-tool]
EOF
    cat > "$_dir/.pre-commit-config.yaml" <<'EOF'
repos:
  - repo: local
    hooks:
      - id: check-unstaged
        name: Block Unstaged Changes
        entry: "bash -c 'source /opt/workspace-ci/lib/checks.sh && ci_check_unstaged'"
        language: system
        pass_filenames: false
        always_run: true
      - id: my-tool
        name: My Custom Tool
        entry: "bash -c 'echo custom; exit 0'"
        language: system
        pass_filenames: false
        always_run: true
        files: \.py$
      - id: my-cargo-lint
        name: My Cargo Lint
        entry: "bash -c 'cargo clippy -- -D warnings'"
        language: system
        pass_filenames: false
        always_run: true
        files: \.rs$
EOF
}

test_scaffold_lift_preserves_custom_hooks() {
    _mk_custom_consumer "$TEST_TMP/sci-custom"
    cd "$PROJECT_DIR"
    bash "$_SCI_SCRIPT" --consumer "$TEST_TMP/sci-custom" --force-precommit --yes > "$TEST_TMP/out" 2>&1
    local _c="$TEST_TMP/sci-custom/.pre-commit-config.yaml"
    grep -q 'My Custom Tool' "$_c" || { echo "lost custom hook name"; return 1; }
    grep -q 'echo custom' "$_c" || { echo "lost custom hook entry"; return 1; }
    grep -q 'My Cargo Lint' "$_c" || { echo "lost cargo hook"; return 1; }
    grep -qF 'files: \.py$' "$_c" || { echo "lost files pattern"; return 1; }
    local _n
    _n="$(awk '/id: my-tool/ { n++ } END { print n + 0 }' "$_c")"
    [[ "$_n" -eq 1 ]] || { echo "custom hook emitted $_n times"; return 1; }
}

test_scaffold_lift_idempotent() {
    _mk_custom_consumer "$TEST_TMP/sci-custom-idem"
    cd "$PROJECT_DIR"
    bash "$_SCI_SCRIPT" --consumer "$TEST_TMP/sci-custom-idem" --force-precommit --yes > "$TEST_TMP/out" 2>&1
    awk '!/^# AUTO-GENERATED by .* \[/' "$TEST_TMP/sci-custom-idem/.pre-commit-config.yaml" > "$TEST_TMP/pass1.yaml"
    bash "$_SCI_SCRIPT" --consumer "$TEST_TMP/sci-custom-idem" --force-precommit --yes > "$TEST_TMP/out" 2>&1
    awk '!/^# AUTO-GENERATED by .* \[/' "$TEST_TMP/sci-custom-idem/.pre-commit-config.yaml" > "$TEST_TMP/pass2.yaml"
    cmp -s "$TEST_TMP/pass1.yaml" "$TEST_TMP/pass2.yaml" || {
        echo "re-scaffold changed the file (not idempotent)"
        return 1
    }
}

test_scaffold_rejects_undefined_custom_id() {
    mkdir -p "$TEST_TMP/sci-reject"
    cat > "$TEST_TMP/sci-reject/ci-profile.yaml" <<'EOF'
version: 1
project: reject-test
tier: strict
languages: [any]
hooks:
  pre-commit: [check-unstaged, ghost-hook]
EOF
    cd "$PROJECT_DIR"
    if bash "$_SCI_SCRIPT" --consumer "$TEST_TMP/sci-reject" --force-precommit --yes > "$TEST_TMP/out" 2>&1; then
        echo "scaffold accepted an undefined custom hook"
        return 1
    fi
    grep -q 'ghost-hook' "$TEST_TMP/out" || { echo "missing diagnostic for ghost-hook"; return 1; }
}

test_scaffold_synthesizes_override_custom_hook() {
    mkdir -p "$TEST_TMP/sci-synth"
    cat > "$TEST_TMP/sci-synth/ci-profile.yaml" <<'EOF'
version: 1
project: synth-test
tier: strict
languages: [any]
hooks:
  pre-commit: [check-unstaged, synth-hook]
overrides:
  synth-hook:
    entry: "bash -c 'echo synthetic; exit 0'"
    name: "Synthetic Hook"
    pass_filenames: false
    always_run: true
EOF
    cd "$PROJECT_DIR"
    bash "$_SCI_SCRIPT" --consumer "$TEST_TMP/sci-synth" --force-precommit --yes > "$TEST_TMP/out" 2>&1
    local _c="$TEST_TMP/sci-synth/.pre-commit-config.yaml"
    grep -q 'id: synth-hook' "$_c" || { echo "synthetic hook not emitted"; return 1; }
    grep -q 'Synthetic Hook' "$_c" || { echo "synthetic hook name lost"; return 1; }
}

test_scaffold_name_override_registered() {
    mkdir -p "$TEST_TMP/sci-name"
    cat > "$TEST_TMP/sci-name/ci-profile.yaml" <<'EOF'
version: 1
project: name-test
tier: strict
languages: [any]
hooks:
  pre-commit: [check-unstaged]
overrides:
  check-unstaged:
    name: "My Renamed Guard"
EOF
    cd "$PROJECT_DIR"
    bash "$_SCI_SCRIPT" --consumer "$TEST_TMP/sci-name" --force-precommit --yes > "$TEST_TMP/out" 2>&1
    grep -q 'My Renamed Guard' "$TEST_TMP/sci-name/.pre-commit-config.yaml" || {
        echo "name override not applied"
        return 1
    }
}

_run_test "scaffold: lifts custom hooks verbatim" test_scaffold_lift_preserves_custom_hooks
_run_test "scaffold: lift is idempotent" test_scaffold_lift_idempotent
_run_test "scaffold: rejects undefined custom id" test_scaffold_rejects_undefined_custom_id
_run_test "scaffold: synthesizes override-defined custom hook" test_scaffold_synthesizes_override_custom_hook
_run_test "scaffold: name override applies to registry hook" test_scaffold_name_override_registered
