#!/usr/bin/env bash
# reinstall-hooks tests: seal-aware orchestration contract.
# Verifies: fast path (unsealed) calls only generate; sealed path orders
# unseal -> generate -> lock; generation failure still re-locks (trap)
# and propagates the failure code. Uses CI_REINSTALL_* seams and a fake
# sudo on PATH: no root required.
#
# Sourced by run_tests_unit.sh: test_helpers.sh is already loaded. Do NOT
# re-source it here (would reset the global test counters).

# Build a fixture git repo at $TEST_TMP/repo with a generated-marker hook
# and fake step scripts logging to $TEST_TMP/order.log.
_make_reinstall_fixture() {
    mkdir -p "$TEST_TMP/repo/.git/hooks" "$TEST_TMP/bin"
    printf '# %s\n#!/usr/bin/env bash\nexit 0\n' "AUTO-GENERATED by generate-hooks" \
        > "$TEST_TMP/repo/.git/hooks/pre-commit"
    git -C "$TEST_TMP/repo" init -q .
    : > "$TEST_TMP/order.log"
    local _step
    for _step in unseal lock generate; do
        cat > "$TEST_TMP/bin/$_step" <<EOF
#!/usr/bin/env bash
echo "$_step \$@" >> "$TEST_TMP/order.log"
exit \${FAKE_${_step}_RC:-0}
EOF
        chmod +x "$TEST_TMP/bin/$_step"
    done
    # Fake sudo: execute the command directly (tests run non-root).
    cat > "$TEST_TMP/bin/sudo" <<'EOF'
#!/usr/bin/env bash
exec "$@"
EOF
    chmod +x "$TEST_TMP/bin/sudo"
}

_run_reinstall() {
    (
        cd "$TEST_TMP/repo"
        PATH="$TEST_TMP/bin:$PATH" \
        CI_REINSTALL_UNSEAL="$TEST_TMP/bin/unseal" \
        CI_REINSTALL_LOCK="$TEST_TMP/bin/lock" \
        CI_REINSTALL_GENERATE="$TEST_TMP/bin/generate" \
        CI_REINSTALL_SEALED="$1" \
            bash "$PROJECT_DIR/scripts/reinstall-hooks"
    )
}

# T1: unsealed fast path -> generate only
test_reinstall_fast_path() {
    _make_reinstall_fixture
    local rc=0
    _run_reinstall 0 >/dev/null 2>&1 || rc=$?
    local order
    order="$(cat "$TEST_TMP/order.log")"
    [[ "$rc" -eq 0 && "$order" == "generate "* ]] || {
        echo "  expected rc=0 and only 'generate', got rc=$rc order:"
        printf '%s\n' "$order" | sed 's/^/    | /'
        return 1
    }
}

# T2: sealed path -> unseal, generate, lock in order
test_reinstall_sealed_cycle() {
    _make_reinstall_fixture
    local rc=0
    _run_reinstall 1 >/dev/null 2>&1 || rc=$?
    local order
    order="$(grep -oE '^(unseal|lock|generate)' "$TEST_TMP/order.log" | tr '\n' ' ')"
    [[ "$rc" -eq 0 && "$order" == "unseal generate lock " ]] || {
        echo "  expected rc=0 and unseal->generate->lock, got rc=$rc order: $order"
        return 1
    }
}

# T3: generation failure -> still re-locks (trap), failure code propagates
test_reinstall_failure_relocks() {
    _make_reinstall_fixture
    local rc=0
    FAKE_generate_RC=7 _run_reinstall 1 >/dev/null 2>&1 || rc=$?
    local order
    order="$(grep -oE '^(unseal|lock|generate)' "$TEST_TMP/order.log" | tr '\n' ' ')"
    [[ "$rc" -eq 7 && "$order" == "unseal generate lock " ]] || {
        echo "  expected rc=7 and unseal->generate->lock, got rc=$rc order: $order"
        return 1
    }
}

_run_test "reinstall-hooks: unsealed fast path"      test_reinstall_fast_path
_run_test "reinstall-hooks: sealed full cycle order" test_reinstall_sealed_cycle
_run_test "reinstall-hooks: failure still re-locks"  test_reinstall_failure_relocks
