#!/usr/bin/env bash

test_reinstall_hooks_exists() {
    [[ -x "$PROJECT_DIR/scripts/reinstall-hooks" ]]
}

test_reinstall_hooks_refuses_non_root() {
    if [[ "$(id -u)" -eq 0 ]]; then
        echo "SKIP: running as root"
        return 0
    fi
    local tmp
    tmp="$(mktemp -d)"
    git -C "$tmp" init -q
    local out rc=0
    out="$(cd "$tmp" && bash "$PROJECT_DIR/scripts/reinstall-hooks" 2>&1)" || rc=$?
    local hooks_written=0
    for stage in pre-commit commit-msg pre-push; do
        [[ -f "$tmp/.git/hooks/$stage" ]] && grep -q 'AUTO-GENERATED by' "$tmp/.git/hooks/$stage" && hooks_written=1
    done
    rm -rf "$tmp"
    if [[ $rc -eq 0 ]]; then
        echo "expected non-zero exit, got 0: $out"
        return 1
    fi
    if [[ $hooks_written -ne 0 ]]; then
        echo "user-owned hooks were written"
        return 1
    fi
    # Refusal may come from either layer: the script's own root check or the
    # shell guard's chattr-strip block. Both fail closed.
    grep -qE 'requires root|BLOCKED' <<<"$out" || { echo "unexpected refusal output: $out"; return 1; }
}

test_reinstall_hooks_no_user_owned_generate_branch() {
    # Regression: the non-root branch that generated user-owned mutable hooks
    # (H5 / ALLOW_UNLOCKED bypass class) must not return.
    if grep -q '"\$BASH" "\$_GENERATE"$' "$PROJECT_DIR/scripts/reinstall-hooks"; then
        echo "user-owned generate branch is back"
        return 1
    fi
}

_run_test "reinstall-hooks exists" test_reinstall_hooks_exists
_run_test "reinstall-hooks refuses non-root" test_reinstall_hooks_refuses_non_root
_run_test "reinstall-hooks has no user-owned generate branch" test_reinstall_hooks_no_user_owned_generate_branch
