"""Tests for ci.check_required_hooks_present: auto-enforcement self-check."""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from ci.check_required_hooks_present import (
    EXIT_INFRA_ERROR,
    EXIT_OK,
    EXIT_VIOLATION,
    REASON_MIN_LEN,
    ExceptionEntry,
    HookEntry,
    HooksManifest,
    QualityExceptions,
    _check_manifest_completeness,
    _check_quality_exceptions,
    _run_invariant_4_entries,
    main,
)


def _make_workspace(tmp_path: Path) -> Path:
    """Create a minimal workspace tree with workspace marker."""
    root = tmp_path / "workspace"
    (root / ".boot-linux").mkdir(parents=True)
    (root / "ci").mkdir(parents=True)
    (root / "config").mkdir()
    return root


def _write_manifest(workspace: Path, hooks: list[dict[str, object]]) -> None:
    cfg = workspace / "config" / "required_hooks.yaml"
    cfg.write_text(yaml.safe_dump({"version": 1, "hooks": hooks}))


def _make_repo_with_hooks(
    parent: Path,
    name: str,
    *,
    pre_commit_markers: list[str] | None = None,
    pre_push_markers: list[str] | None = None,
) -> Path:
    repo = parent / name
    (repo / ".git" / "hooks").mkdir(parents=True)
    pre_commit = (
        "#!/usr/bin/env bash\n"
        "# AUTO-GENERATED by /opt/workspace-ci/scripts/generate-hooks\n"
        "source /opt/workspace-ci/lib/ci.sh\n"
    )
    for m in pre_commit_markers or []:
        pre_commit += f"# === Hook: {m} ===\n"
    (repo / ".git" / "hooks" / "pre-commit").write_text(pre_commit)
    pre_push = (
        "#!/usr/bin/env bash\n"
        "# AUTO-GENERATED by /opt/workspace-ci/scripts/generate-hooks\n"
        "source /opt/workspace-ci/lib/ci.sh\n"
    )
    for m in pre_push_markers or []:
        pre_push += f"# === Hook: {m} ===\n"
    (repo / ".git" / "hooks" / "pre-push").write_text(pre_push)
    return repo


# ── unit: invariant 1: manifest completeness ─────────────────────────────────


def test_manifest_completeness_passes_when_all_registered(tmp_path: Path) -> None:
    root = _make_workspace(tmp_path)
    (root / "ci" / "check_foo.py").write_text("")
    manifest = HooksManifest(
        hooks=[
            HookEntry(
                id="check-foo",
                kind="python_module",
                entry="ci.check_foo",
                stage="pre-commit",
            ),
        ],
    )
    assert _check_manifest_completeness(root, manifest) == []


def test_manifest_completeness_flags_missing(tmp_path: Path) -> None:
    root = _make_workspace(tmp_path)
    (root / "ci" / "check_foo.py").write_text("")
    manifest = HooksManifest(hooks=[])
    issues = _check_manifest_completeness(root, manifest)
    assert len(issues) == 1
    assert "check_foo.py" in issues[0]


def test_manifest_completeness_handles_missing_dir(tmp_path: Path) -> None:
    issues = _check_manifest_completeness(tmp_path, HooksManifest())
    assert len(issues) == 1
    assert "not found" in issues[0]


# ── unit: invariant 2: quality_exceptions schema ─────────────────────────────


def _manifest_with_one_exemptable() -> HooksManifest:
    return HooksManifest(
        hooks=[
            HookEntry(
                id="check-dead-code",
                kind="shell",
                entry="ci_check_dead_code",
                stage="pre-push",
                mandatory=False,
            ),
            HookEntry(
                id="ci-lint",
                kind="makefile_target",
                entry="lint",
                stage="pre-commit",
                mandatory=True,
            ),
        ],
    )


def test_quality_exceptions_passes_for_valid_entry() -> None:
    manifest = _manifest_with_one_exemptable()
    excs = QualityExceptions(
        exceptions=[
            ExceptionEntry(
                hook="check-dead-code",
                reason="Vendored adapters with dynamic imports: unanalysable.",
                paths=["vendor/"],
                added_by="dev@example.com",
            ),
        ],
    )
    assert _check_quality_exceptions(excs, manifest) == []


def test_quality_exceptions_rejects_unknown_hook() -> None:
    excs = QualityExceptions(
        exceptions=[
            ExceptionEntry(
                hook="bogus",
                reason="some reason that is at least twenty chars long",
                paths=["x/"],
                added_by="d@e.com",
            ),
        ],
    )
    issues = _check_quality_exceptions(excs, _manifest_with_one_exemptable())
    assert any("not in required_hooks.yaml" in i for i in issues)


def test_quality_exceptions_rejects_mandatory_hook() -> None:
    excs = QualityExceptions(
        exceptions=[
            ExceptionEntry(
                hook="ci-lint",
                reason="some reason that is at least twenty chars long",
                paths=["x/"],
                added_by="d@e.com",
            ),
        ],
    )
    issues = _check_quality_exceptions(excs, _manifest_with_one_exemptable())
    assert any("mandatory" in i for i in issues)


def test_quality_exceptions_rejects_empty_paths() -> None:
    excs = QualityExceptions(
        exceptions=[
            ExceptionEntry(
                hook="check-dead-code",
                reason="some reason that is at least twenty chars long",
                paths=[],
                added_by="d@e.com",
            ),
        ],
    )
    issues = _check_quality_exceptions(excs, _manifest_with_one_exemptable())
    assert any("non-empty" in i for i in issues)


def test_quality_exceptions_rejects_short_reason() -> None:
    excs = QualityExceptions(
        exceptions=[
            ExceptionEntry(
                hook="check-dead-code",
                reason="short",
                paths=["x/"],
                added_by="d@e.com",
            ),
        ],
    )
    issues = _check_quality_exceptions(excs, _manifest_with_one_exemptable())
    assert any("shorter than required" in i for i in issues)
    assert REASON_MIN_LEN > 0


def test_quality_exceptions_rejects_missing_added_by() -> None:
    excs = QualityExceptions(
        exceptions=[
            ExceptionEntry(
                hook="check-dead-code",
                reason="some reason that is at least twenty chars long",
                paths=["x/"],
                added_by="",
            ),
        ],
    )
    issues = _check_quality_exceptions(excs, _manifest_with_one_exemptable())
    assert any("added_by" in i for i in issues)


# ── integration: main() entry point ───────────────────────────────────────────


_BUILTIN_BLOCKS = (
    "# === quality_exceptions.yaml preflight (mandatory) ===\n"
    "# CI-BUILTIN-EXEMPTION-COMPLIANCE\n"
)

# Baseline safety-marked hook (makefile_target: no lib-resolution coupling).
_SAFETY_HOOK: dict[str, object] = {
    "id": "baseline-safety",
    "kind": "makefile_target",
    "entry": "check-safety",
    "stage": "pre-commit",
    "mandatory": True,
    "safety": True,
}


def _setup_strict_repo_with_full_contract(workspace: Path, name: str) -> Path:
    project = workspace / "projects" / name
    project.mkdir(parents=True)
    (project / "quality_exceptions.yaml").write_text(
        yaml.safe_dump({"version": 1, "project": name, "exceptions": []}),
    )
    (project / ".git" / "hooks").mkdir(parents=True)
    (project / ".git" / "hooks" / "pre-commit").write_text(
        "#!/usr/bin/env bash\n"
        "# AUTO-GENERATED by /opt/workspace-ci/scripts/generate-hooks\n"
        "source /opt/workspace-ci/lib/ci.sh\n"
        f"{_BUILTIN_BLOCKS}"
        "# === Hook: ci-lint ===\n"
        "# === Hook: ci-type-check ===\n"
        "# === Hook: baseline-safety ===\n",
    )
    (project / ".git" / "hooks" / "pre-push").write_text(
        "#!/usr/bin/env bash\n"
        "# AUTO-GENERATED by /opt/workspace-ci/scripts/generate-hooks\n"
        "source /opt/workspace-ci/lib/ci.sh\n"
        f"{_BUILTIN_BLOCKS}",
    )
    return project


def test_main_passes_for_strict_compliant_project(tmp_path: Path) -> None:
    root = _make_workspace(tmp_path)
    _write_manifest(
        root,
        [
            {
                "id": "ci-lint",
                "kind": "makefile_target",
                "entry": "lint",
                "stage": "pre-commit",
                "mandatory": True,
            },
            {
                "id": "ci-type-check",
                "kind": "makefile_target",
                "entry": "type-check",
                "stage": "pre-commit",
                "mandatory": True,
            },
            dict(_SAFETY_HOOK),
        ],
    )
    project = _setup_strict_repo_with_full_contract(root, "X")
    assert main(["--project", str(project), "--quiet"]) == EXIT_OK


def test_main_fails_when_quality_exceptions_missing(tmp_path: Path) -> None:
    root = _make_workspace(tmp_path)
    _write_manifest(root, [])
    project = root / "projects" / "X"
    (project / ".git" / "hooks").mkdir(parents=True)
    assert main(["--project", str(project), "--quiet"]) == EXIT_VIOLATION


def test_main_fails_when_builtin_marker_missing(tmp_path: Path) -> None:
    """Invariant 3: rendered hooks must carry the compliance blocks."""
    root = _make_workspace(tmp_path)
    _write_manifest(root, [])
    project = _setup_strict_repo_with_full_contract(root, "X")
    hook = project / ".git" / "hooks" / "pre-commit"
    hook.write_text(
        "#!/usr/bin/env bash\n"
        "source /opt/workspace-ci/lib/ci.sh\n"
        "# === Hook: ci-lint ===\n",
    )
    rc = main(["--project", str(project), "--quiet"])
    assert rc == EXIT_VIOLATION


def test_main_fails_when_mandatory_hook_marker_missing(
    tmp_path: Path,
) -> None:
    """Invariant 3: applicable mandatory hooks must be rendered."""
    root = _make_workspace(tmp_path)
    _write_manifest(
        root,
        [
            {
                "id": "ci-lint",
                "kind": "makefile_target",
                "entry": "lint",
                "stage": "pre-commit",
                "mandatory": True,
            },
        ],
    )
    project = _setup_strict_repo_with_full_contract(root, "X")
    hook = project / ".git" / "hooks" / "pre-commit"
    hook.write_text(hook.read_text().replace("# === Hook: ci-lint ===\n", ""))
    assert main(["--project", str(project), "--quiet"]) == EXIT_VIOLATION


def test_main_passes_when_nonmandatory_hook_unrendered(
    tmp_path: Path,
) -> None:
    """Invariant 3: optional hooks are not required in rendered hooks."""
    root = _make_workspace(tmp_path)
    _write_manifest(
        root,
        [
            {
                "id": "ci-optional",
                "kind": "makefile_target",
                "entry": "whatever",
                "stage": "pre-commit",
                "mandatory": False,
            },
            dict(_SAFETY_HOOK),
        ],
    )
    project = _setup_strict_repo_with_full_contract(root, "X")
    assert main(["--project", str(project), "--quiet"]) == EXIT_OK


def test_main_returns_infra_error_when_no_workspace(tmp_path: Path) -> None:
    assert main(["--project", str(tmp_path), "--quiet"]) == EXIT_INFRA_ERROR


def test_main_returns_infra_error_when_no_manifest(tmp_path: Path) -> None:
    root = _make_workspace(tmp_path)
    project = root / "projects" / "X"
    project.mkdir(parents=True)
    assert main(["--project", str(project), "--quiet"]) == EXIT_INFRA_ERROR


def test_main_emits_ok_lines_when_not_quiet(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    root = _make_workspace(tmp_path)
    _write_manifest(
        root,
        [
            {
                "id": "ci-lint",
                "kind": "makefile_target",
                "entry": "lint",
                "stage": "pre-commit",
                "mandatory": True,
            },
            dict(_SAFETY_HOOK),
        ],
    )
    project = _setup_strict_repo_with_full_contract(root, "X")
    rc = main(["--project", str(project)])
    assert rc == EXIT_OK
    captured = capsys.readouterr()
    assert "[OK]" in captured.out


def test_main_accepts_workspace_root(tmp_path: Path) -> None:
    root = _make_workspace(tmp_path)
    _write_manifest(root, [dict(_SAFETY_HOOK)])
    (root / "quality_exceptions.yaml").write_text(
        yaml.safe_dump({"version": 1, "project": "ROOT", "exceptions": []}),
    )
    (root / ".git" / "hooks").mkdir(parents=True)
    (root / ".git" / "hooks" / "pre-commit").write_text(
        "#!/usr/bin/env bash\n"
        "# AUTO-GENERATED by /opt/workspace-ci/scripts/generate-hooks\n"
        "source /opt/workspace-ci/lib/ci.sh\n"
        f"{_BUILTIN_BLOCKS}"
        "# === Hook: baseline-safety ===\n",
    )
    rc = main(["--project", str(root), "--quiet"])
    assert rc == EXIT_OK


