#!/usr/bin/env bash

echo "=== generate-hooks tests ==="

test_generate_hooks_rejects_empty_entry() {
    local root="$TEST_TMP/hooks"
    mkdir -p "$root"
    git -C "$root" init -q
    printf 'repos:\n  - repo: local\n    hooks:\n      - id: empty\n        entry: ""\n        language: system\n        stages: [pre-commit]\n' > "$root/.pre-commit-config.yaml"
    ! (cd "$root" && bash "$PROJECT_DIR/scripts/generate-hooks")
}
_run_test "generate-hooks rejects empty entry" test_generate_hooks_rejects_empty_entry

test_generate_hooks_binds_protected_deployment() {
    local root="$TEST_TMP/protected-hooks" output="$TEST_TMP/generated"
    local python_path="/opt/workspace-ci/.boot-linux/bin/uv run --project /opt/workspace-ci --no-sync python"
    mkdir -p "$root" "$output"
    git -C "$root" init -q
    printf 'repos:\n  - repo: local\n    hooks:\n      - id: check\n        name: Check\n        entry: "true"\n        language: system\n        stages: [pre-commit]\n      - id: python-check\n        name: Python check\n        entry: "uv run python -m ci.check_dependency_versions validate"\n        language: system\n        stages: [pre-commit]\n' > "$root/.pre-commit-config.yaml"
    (cd "$root" && bash "$PROJECT_DIR/scripts/generate-hooks" --output-dir "$output")
    grep -q 'AUTO-GENERATED by /opt/workspace-ci' "$output/pre-commit"
    grep -q 'source /opt/workspace-ci/lib/ci.sh' "$output/pre-commit"
    grep -q "$python_path -m ci.check_dependency_versions validate" "$output/pre-commit"
    ! grep -q 'projects/CI' "$output/pre-commit"
}
_run_test "generate-hooks binds protected deployment" test_generate_hooks_binds_protected_deployment

test_generate_hooks_advisory_wrapper_is_non_failing() {
    local root="$TEST_TMP/advisory-hooks" output="$TEST_TMP/advisory-generated"
    mkdir -p "$root" "$output"
    git -C "$root" init -q
    printf 'repos:\n  - repo: local\n    hooks:\n      - id: blocker\n        name: Blocking Gate\n        entry: "true"\n        language: system\n        stages: [pre-push]\n      - id: advisory-one\n        name: Advisory Gate\n        entry: "false"\n        language: system\n        stages: [pre-push]\n        advisory: true\n' > "$root/.pre-commit-config.yaml"
    (cd "$root" && bash "$PROJECT_DIR/scripts/generate-hooks" --output-dir "$output")
    # Advisory hook: rc captured, reported with ci_info, never exits 1.
    grep -q 'false || _advisory_rc=$?' "$output/pre-push"
    grep -q 'ADVISORY (non-blocking): Advisory Gate' "$output/pre-push"
    # Blocking hook: unchanged fail-closed wrapper.
    grep -q 'true || { ci_fail "Blocking Gate"; exit 1; }' "$output/pre-push"
    # Advisory wrapper must not contain the fail-closed wrapper for the
    # advisory entry.
    ! grep -q 'false || { ci_fail' "$output/pre-push"
}
_run_test "generate-hooks advisory wrapper is non-failing" test_generate_hooks_advisory_wrapper_is_non_failing

test_generate_hooks_refuses_unresolved_shell_entry() {
    local root="$TEST_TMP/unresolved-hooks" output="$TEST_TMP/unresolved-generated"
    mkdir -p "$root" "$output"
    git -C "$root" init -q
    # The 2026-08-24 incident class: catalog entry references a function
    # that no lib module defines (ci_check_portable_shell was dropped
    # from checks_files.sh while the entry survived).
    printf 'repos:\n  - repo: local\n    hooks:\n      - id: ghost\n        name: Ghost Gate\n        entry: "bash -c \x27source lib/checks.sh && ci_check_ghost_function\x27"\n        language: system\n        stages: [pre-commit]\n' > "$root/.pre-commit-config.yaml"
    local out rc=0
    out="$(cd "$root" && bash "$PROJECT_DIR/scripts/generate-hooks" --output-dir "$output" 2>&1)" || rc=$?
    [[ $rc -ne 0 ]] || { echo "expected generation refusal for unresolved entry"; return 1; }
    echo "$out" | grep -q "ci_check_ghost_function"
    echo "$out" | grep -q "no lib module defines it"
}

test_generate_hooks_refuses_missing_python_module() {
    local root="$TEST_TMP/ghostmod-hooks" output="$TEST_TMP/ghostmod-generated"
    mkdir -p "$root" "$output"
    git -C "$root" init -q
    printf 'repos:\n  - repo: local\n    hooks:\n      - id: ghostmod\n        name: Ghost Module\n        entry: "uv run python -m ci.ghost_module_subsystem"\n        language: system\n        stages: [pre-commit]\n' > "$root/.pre-commit-config.yaml"
    local out rc=0
    out="$(cd "$root" && bash "$PROJECT_DIR/scripts/generate-hooks" --output-dir "$output" 2>&1)" || rc=$?
    [[ $rc -ne 0 ]] || { echo "expected generation refusal for missing module"; return 1; }
    echo "$out" | grep -q "ci.ghost_module_subsystem"
}

_run_test "generate-hooks refuses unresolved shell entry" test_generate_hooks_refuses_unresolved_shell_entry
_run_test "generate-hooks refuses missing python module" test_generate_hooks_refuses_missing_python_module
